
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39225_development


test:
  <<: *default
  database: furima_39225_test

production:
  <<: *default
  database: furima_39225_production
  username: furima_39225
  password: <%= ENV['FURIMA_39225_DATABASE_PASSWORD'] %>
